import React, { useState } from "react";
import { View, ScrollView, TextInput } from "react-native";
import { Text, Button, Card } from "react-native-paper";
import { SafeAreaView } from "react-native-safe-area-context";
import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import CustomAppBar from "@/components/utils/CustomAppBar";
import { useTheme } from "@/lib/hooks/useTheme";

interface AlertDetailsProps {
  route?: {
    params: {
      alertType: string;
      value: string;
      timestamp: string;
      safeRange: string;
      riskLevel: string;
      recommendedAction: string;
    };
  };
}

const AlertDetailsScreen: React.FC<AlertDetailsProps> = ({ route }) => {
  const [notes, setNotes] = useState("");
  const router = useRouter();
  const { colors, typo, layout } = useTheme();

  // Default data (replace with route params in real implementation)
  const alertData = route?.params || {
    alertType: "High Blood Pressure",
    value: "150/95 mmHg",
    timestamp: "Today, 2:30 PM",
    safeRange: "Below 130/85 mmHg",
    riskLevel: "Moderate",
    recommendedAction:
      "Contact your healthcare provider if symptoms persist. Monitor your blood pressure every 2 hours.",
  };

  const shareData = {
    message: `🚨 Vitali-T Health Alert\n\nAlert Type: ${alertData.alertType}\nValue: ${alertData.value}\nTime: ${alertData.timestamp}\nRisk Level: ${alertData.riskLevel}\nSafe Range: ${alertData.safeRange}\nRecommended Action: ${alertData.recommendedAction}\n${notes ? `Additional Notes: ${notes}` : ""}\n\nGenerated by Vitali-T - Maternal Health Monitoring`,
    title: `Vitali-T Alert: ${alertData.alertType}`,
  };

  const handleMarkAsAcknowledged = () => {
    // Add acknowledgment logic with animation
    console.log("Alert marked as acknowledged");
    router.back();
  };

  return (
    <SafeAreaView
      style={{
        flex: 1,
        backgroundColor: colors.background,
      }}
    >
      <CustomAppBar
        title="Alert Details"
        rightAction="share"
        shareData={shareData}
      />

      <ScrollView
        style={{
          flex: 1,
          paddingHorizontal: layout.spacing.lg,
        }}
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{
          padding: layout.spacing.sm,
          paddingBottom: layout.spacing.lg,
        }}
      >
        {/* Alert Icon */}
        <View
          style={{
            alignItems: "center",
            marginBottom: layout.spacing.lg,
          }}
        >
          <View
            style={{
              width: 80,
              height: 80,
              borderRadius: layout.borderRadius.large,
              backgroundColor: colors.errorLight,
              justifyContent: "center",
              alignItems: "center",
              borderWidth: 2,
              borderColor: colors.errorGradientStart,
            }}
          >
            <MaterialIcons name="warning" size={32} color={colors.error} />
          </View>
        </View>

        {/* Alert Title and Value */}
        <Text
          style={{
            fontSize: typo.h5.fontSize,
            fontWeight: "600",
            color: colors.text,
            textAlign: "center",
            marginBottom: layout.spacing.sm,
            ...typo.h5,
          }}
        >
          {alertData.alertType}
        </Text>
        <Text
          style={{
            fontSize: typo.h3.fontSize,
            fontWeight: "700",
            color: colors.error,
            textAlign: "center",
            marginBottom: layout.spacing.sm,
            ...typo.h3,
          }}
        >
          {alertData.value}
        </Text>
        <Text
          style={{
            fontSize: typo.body2.fontSize,
            color: colors.text,
            textAlign: "center",
            marginBottom: layout.spacing.lg,
            ...typo.body2,
          }}
        >
          {alertData.timestamp}
        </Text>

        {/* Safe Range */}
        <Card
          style={{
            marginBottom: layout.spacing.sm,
            backgroundColor: colors.card,
            elevation: layout.elevation,
          }}
        >
          <Card.Content
            style={{
              flexDirection: "row",
              alignItems: "center",
            }}
          >
            <MaterialIcons
              name="check-circle"
              size={20}
              color={colors.success}
            />
            <View
              style={{
                marginLeft: layout.spacing.sm,
                flex: 1,
              }}
            >
              <Text
                style={{
                  fontSize: typo.body2.fontSize,
                  fontWeight: "600",
                  color: colors.text,
                  marginBottom: layout.spacing.xs,
                  ...typo.body2,
                }}
              >
                Safe Range
              </Text>
              <Text
                style={{
                  fontSize: typo.body3.fontSize,
                  color: colors.text,
                  ...typo.body3,
                }}
              >
                {alertData.safeRange}
              </Text>
            </View>
          </Card.Content>
        </Card>

        {/* Risk Level */}
        <Card
          style={{
            marginBottom: layout.spacing.sm,
            backgroundColor: colors.card,
            elevation: layout.elevation,
          }}
        >
          <Card.Content
            style={{
              flexDirection: "row",
              alignItems: "center",
            }}
          >
            <MaterialIcons name="assessment" size={20} color={colors.warning} />
            <View
              style={{
                marginLeft: layout.spacing.sm,
                flex: 1,
              }}
            >
              <Text
                style={{
                  fontSize: typo.body2.fontSize,
                  fontWeight: "600",
                  color: colors.text,
                  marginBottom: layout.spacing.xs,
                  ...typo.body2,
                }}
              >
                Risk Level
              </Text>
              <Text
                style={{
                  fontSize: typo.body3.fontSize,
                  color: colors.text,
                  ...typo.body3,
                }}
              >
                {alertData.riskLevel}
              </Text>
            </View>
          </Card.Content>
        </Card>

        {/* Recommended Action */}
        <Card
          style={{
            marginVertical: layout.spacing.sm,
            backgroundColor: colors.card,
            elevation: layout.elevation,
          }}
        >
          <Card.Content>
            <View
              style={{
                flexDirection: "row",
                alignItems: "center",
                marginBottom: layout.spacing.sm,
              }}
            >
              <MaterialIcons name="lightbulb" size={20} color={colors.info} />
              <Text
                style={{
                  fontSize: typo.body2.fontSize,
                  fontWeight: "600",
                  color: colors.text,
                  marginLeft: layout.spacing.sm,
                  ...typo.body2,
                }}
              >
                Recommended Action
              </Text>
            </View>
            <Text
              style={{
                fontSize: typo.body3.fontSize,
                color: colors.text,
                lineHeight: typo.body1.lineHeight,
                ...typo.body3,
              }}
            >
              {alertData.recommendedAction}
            </Text>
          </Card.Content>
        </Card>

        {/* Additional Notes */}
        <View
          style={{
            marginTop: layout.spacing.lg,
          }}
        >
          <Text
            style={{
              fontSize: typo.body2.fontSize,
              fontWeight: "600",
              color: colors.text,
              marginBottom: layout.spacing.sm,
              ...typo.body2,
            }}
          >
            Additional Notes
          </Text>
          <TextInput
            style={{
              borderWidth: 1,
              borderColor: colors.border,
              borderRadius: layout.borderRadius.medium,
              padding: layout.spacing.sm,
              fontSize: typo.input.fontSize,
              color: colors.text,
              backgroundColor: colors.card,
              minHeight: 100,
              textAlignVertical: "top",
              ...typo.input,
            }}
            placeholder="Add any relevant notes about this alert..."
            placeholderTextColor={colors.text}
            value={notes}
            onChangeText={setNotes}
            multiline
            numberOfLines={4}
          />
        </View>
      </ScrollView>

      {/* Mark as Acknowledged Button */}
      <View
        style={{
          padding: layout.spacing.sm,
          paddingBottom: layout.spacing.lg,
        }}
      >
        <Button
          mode="contained"
          style={{
            backgroundColor: colors.primary,
            borderRadius: layout.borderRadius.large,
            paddingVertical: layout.spacing.sm,
          }}
          labelStyle={{
            fontSize: typo.button.fontSize,
            fontWeight: "600",
            color: colors.textInverse,
            ...typo.button,
          }}
          onPress={handleMarkAsAcknowledged}
        >
          Mark as Acknowledged
        </Button>
      </View>
    </SafeAreaView>
  );
};

export default AlertDetailsScreen;
